name: Commit Message Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  validate_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages
        uses: commit-check/commit-check-action@v0.6.1
        with:
          message: true
          pr-comments: true
          # Use the built-in GITHUB_TOKEN instead of a PAT
          github_token: ${{ secrets.GITHUB_TOKEN }}