name: Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto Label PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}   # Use your PAT here
          configuration-path: .github/labeler.yml
          sync-labels: true                      # Let it assign existing labels only
          dot: true
