# .github/workflows/labeler.yml
name: Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Auto Label PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # Optional: Specify the path to your labeler configuration file if it's not .github/labeler.yml
          # configuration-path: .github/my-custom-label-config.yml