# .github/workflows/pr-title-check.yml
name: PR Title Check

on:
  pull_request:
    # This workflow runs when a pull request is opened,
    # edited (e.g., title changed), synchronized (new commits pushed),
    # or reopened.
    types: [opened, edited, synchronize, reopened]

jobs:
  validate_pr_title:
    runs-on: ubuntu-latest
    permissions:
      # Required for the action to be able to set a status check on the PR
      pull-requests: write

    steps:
      - name: Validate PR title with Conventional Commits
        # Uses a popular action designed for this purpose
        uses: amannn/action-semantic-pull-request@v5 # Using v5, adjust if a newer stable version is available

        env:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          # and gives the action necessary permissions to interact with the PR.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}